// Mocks generated by Mockito 5.0.14 from annotations
// in h264/example/ios/.symlinks/plugins/h264/test/h264_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:h264/h264.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [H264].
///
/// See the documentation for Mockito's code generation for more information.
class MockH264 extends _i1.Mock implements _i2.H264 {
  MockH264() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> decodeFrame(
          String? source, String? target, int? width, int? height) =>
      (super.noSuchMethod(
          Invocation.method(#decodeFrame, [source, target, width, height]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  String toString() => super.toString();
}
