name: h264_example
description: Demonstrates how to use the h264 plugin.
publish_to: 'none'

dependencies:
  path_provider: ^1.6.7
  flutter:
    sdk: flutter

dev_dependencies:
  e2e: ^0.4.2
  flutter_test:
    sdk: flutter

  h264:
    path: ../
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/samples/
