name: h264_example
description: Demonstrates how to use the h264 plugin.
publish_to: 'none'

dependencies:
  path_provider: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  h264:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/samples/