name: h264_example
description: Demonstrates how to use the h264 plugin.
publish_to: 'none'

dependencies:
  path_provider: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  h264:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/samples/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"
