name: h264
description: Decode single H264 or H265 keyframes frames into images.
version: 0.4.0
homepage: https://github.com/ened/flutter_plugin_h264

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.0.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.h264
        pluginClass: H264Plugin
      ios:
        pluginClass: H264Plugin
    
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"
       
